apiVersion: v1
kind: Service
metadata:
  name: production
  namespace: production
spec:
  ports:
    - nodePort: 31111
      port: 3000
      targetPort: 3000
  selector:
    app: example
  type: NodePort
